version: '3'

services:
  ttsmaker-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - CACHE_ENABLED=true
      - CACHE_EXPIRE=3600
      - HEADLESS=true
      - TIMEOUT=30
    restart: unless-stopped 